---
title: "sub_table_SW"
author: "Thomas A."
date: "30/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(ggpubr)
library(car)
library(haven)
library(data.table)
library(visreg)
library(dplyr)
library(tidyr)
library(reshape2)
library(rstatix)
library(JWileymisc)
library(lme4)
library(lmerTest)
library(multilevelTools)
library(tidyverse)
library(Rmisc)

SWS_data_perElec <- read.table("../Tables/CTET_SWdetection_thr90_allE_P2P_behav_vec_full.txt", header = TRUE, sep = ",", stringsAsFactors = FALSE)

#SWS_data <- read.table("../Tables/CTET_SWdetection_avDens_behav_vec.txt", header = TRUE, sep = ",", stringsAsFactors = FALSE)

##until you get data on which electrodes to use: 
SWS_data <- SWS_data_perElec

#SWS_data<-SWS_data_perElec[SWS_data_perElec$Elec=='Fpz',]

names(SWS_data)[names(SWS_data) == "Drug"] <- "Treatment"

SWS_data$Treatment<-as.factor(SWS_data$Treatment)

SWS_data$Treatment<-relevel(SWS_data$Treatment,"PLA")
```

```{r}
#detach("package:multilevelTools", unload=TRUE)
#detach("package:lmerTest", unload=TRUE)

lm.FA0 <- lmer(FA ~ 1 + (1|SubID), data = SWS_data, REML = FALSE)

##Effects of treatment on false alarms 
lm.FA1 <- lmer(FA ~ 1 + Treatment + (1|SubID), data = SWS_data, REML = FALSE)

#Added effects of block number on false alarm
lm.FA2 <- lmer(FA ~ 1 + Treatment + BlockN + (1|SubID), data = SWS_data, REML = FALSE)

#Added effects of slow wave density on false alarm on the winning model
lm.FA3 <- lmer(FA ~ 1 + Treatment + BlockN + SWdens + (1|SubID), data = SWS_data, REML = FALSE)

#Effects of just slow wave density and block number on false alarm
lm.FA4 <- lmer(FA ~ 1 + BlockN + SWdens + (1|SubID), data = SWS_data, REML = FALSE)

##Anova to see which one has the most interaction
anova(lm.FA0,lm.FA1,lm.FA2,lm.FA3)

```

```{r}
#detach("package:multilevelTools", unload=TRUE)
#detach("package:lmerTest", unload=TRUE)

##Misses 
lm.Miss0 <- lmer(Miss ~ 1 + (1|SubID), data = SWS_data, REML = FALSE)

##Effects of treatment on misses 
lm.Miss1 <- lmer(Miss ~ 1 + Treatment + (1|SubID), data = SWS_data, REML = FALSE)

#Added effects of block number on misses
lm.Miss2 <- lmer(Miss ~ 1 + Treatment + BlockN + (1|SubID), data = SWS_data, REML = FALSE)

##Added effects of block number as an interaction on misses 
lm.Miss3 <- lmer(Miss ~ 1 + Treatment + BlockN + SWdens + (1|SubID), data = SWS_data, REML = FALSE)

##Added effects of slow wave density on misses on the winning model
lm.Miss4 <- lmer(Miss ~ 1 + Treatment*BlockN + SWdens + (1|SubID), data = SWS_data, REML = FALSE)

##Effects of just slow wave density and block number on misses
lm.Miss5 <- lmer(Miss ~ 1  + BlockN + SWdens + (1|SubID), data = SWS_data, REML = FALSE)

##Anova to see which one has the most interaction
anova(lm.Miss0,lm.Miss1,lm.Miss2,lm.Miss3)

```

```{r}
##Hit Rate  
lm.HR0 <- lmer(Hit_RT ~ 1 + (1|SubID), data = SWS_data, REML = FALSE)

##Effects of treatment on hit rate 
lm.HR1 <- lmer(Hit_RT ~ 1 + Treatment + (1|SubID), data = SWS_data, REML = FALSE)

##Added effects of block number on hit rate  
lm.HR2 <- lmer(Hit_RT ~ 1 + Treatment + BlockN + (1|SubID), data = SWS_data, REML = FALSE)

##Added effects of block number as an interaction on hit rate  
lm.HR3 <- lmer(Hit_RT ~ 1 + Treatment + BlockN + SWdens + (1|SubID), data = SWS_data, REML = FALSE)

##Added effects of slow wave density on hit rate on the winning model
lm.HR4 <- lmer(Hit_RT ~ 1 + Treatment + SWdens + (1|SubID), data = SWS_data, REML = FALSE)

##Effects of just slow wave density and block number on reaction time
lm.HR5 <- lmer(Hit_RT ~ 1  + BlockN + SWdens + (1|SubID), data = SWS_data, REML = FALSE)


##Anova to see which one has the most interaction
anova(lm.HR0,lm.HR1,lm.HR2,lm.HR3)

```


```{r}
#GRAPHS WITH DATA ON PARTICULAR POINTS 

SWS_data$Treatment<-ordered(SWS_data$Treatment, c("PLA","MPH","ATM","CIT"))

#aggdata.fa <- aggregate(SWS_data[, 2], list( Treatment = SWS_data$Treatment, FA = SWS_data$FA, SWdens = SWS_data$SWdens), mean)
#colnames(aggdata.fa) = c("Treatment","FA", "SWdens","SubID")
SWS_data$Elec<-0
agg_SWS_data<-aggregate(. ~ SubID+Treatment, data = SWS_data, FUN = mean)

##Scatterplot of slow wave density and false alarm 
ggplot(agg_SWS_data, aes (x = SWdens, y = FA)) + geom_point(alpha = .5)+ geom_smooth(method=lm, se = FALSE)+ scale_colour_manual(values = c("#666666", "#d95f02", "#7570b3", "#1b9e77"))
cor.test(agg_SWS_data$SWdens, agg_SWS_data$FA)

##Scatterplot of slow wave density and misses
ggplot(agg_SWS_data, aes (x = SWdens, y = Miss)) + geom_point(alpha = .7)+ geom_smooth(method=lm, se = FALSE) + scale_colour_manual(values = c("#666666", "#d95f02", "#7570b3", "#1b9e77"))
cor.test(agg_SWS_data$SWdens, agg_SWS_data$Miss)

##Scatterplot of slow wave density and reaction time
ggplot(agg_SWS_data, aes (x = SWdens, y = Hit_RT)) + geom_point(alpha = .5)+ geom_smooth(method=lm, se = FALSE) + scale_colour_manual(values = c("#666666", "#d95f02", "#7570b3", "#1b9e77"))
cor.test(agg_SWS_data$SWdens, agg_SWS_data$Hit_RT)

```
```{r}
# GRAPHS WITH COLOUR 
SWS_data$Treatment<-ordered(SWS_data$Treatment, c("PLA","MPH","ATM","CIT"))

#aggdata.fa <- aggregate(SWS_data[, 2], list( Treatment = SWS_data$Treatment, FA = SWS_data$FA, SWdens = SWS_data$SWdens), mean)
#colnames(aggdata.fa) = c("Treatment","FA", "SWdens","SubID")
SWS_data$Elec<-0
agg_SWS_data1<-aggregate(. ~ SubID+Treatment+FA+Miss+Hit_RT, data = SWS_data, FUN = mean)

##Scatterplot of slow wave density and false alarm 
ggplot(agg_SWS_data1, aes (x = SWdens, y = FA, colour = Treatment)) + geom_point(alpha = .5)+ geom_smooth(method=lm, se = FALSE)+ scale_colour_manual(values = c("#666666", "#d95f02", "#7570b3", "#1b9e77"))
cor.test(agg_SWS_data$SWdens, agg_SWS_data$FA)

##Scatterplot of slow wave density and misses
ggplot(agg_SWS_data1, aes (x = SWdens, y = Miss, colour = Treatment)) + geom_point(alpha = .7)+ geom_smooth(method=lm, se = FALSE) + scale_colour_manual(values = c("#666666", "#d95f02", "#7570b3", "#1b9e77"))
cor.test(agg_SWS_data$SWdens, agg_SWS_data$Miss)

##Scatterplot of slow wave density and reaction time
ggplot(agg_SWS_data1, aes (x = SWdens, y = Hit_RT, colour = Treatment)) + geom_point(alpha = .5)+ geom_smooth(method=lm, se = FALSE) + scale_colour_manual(values = c("#666666", "#d95f02", "#7570b3", "#1b9e77"))
cor.test(agg_SWS_data$SWdens, agg_SWS_data$Hit_RT)

```

```{r}
#Subsetting Data

##false alarm
fa.data <- c("SubID","Treatment", "FA", "SWdens")
fa.dataset <- SWS_data[fa.data]

fa.mph <- fa.dataset[which(fa.dataset$Treatment == c('PLA', 'MPH')), ]
fa.atm <- fa.dataset[which(fa.dataset$Treatment == c('PLA', 'ATM')), ]
fa.cit <-fa.dataset[which(fa.dataset$Treatment == c('PLA', 'CIT')), ]
  
##misses 
miss.data <- c("SubID","Treatment", "Miss", "SWdens")
miss.dataset <- SWS_data[miss.data]

miss.mph <- fa.dataset[which(miss.dataset$Treatment == c('PLA', 'MPH')), ]
miss.atm <- fa.dataset[which(miss.dataset$Treatment == c('PLA', 'ATM')), ]
miss.cit <-fa.dataset[which(miss.dataset$Treatment == c('PLA', 'CIT')), ]

##reaction time 
hr.data <- c("SubID","Treatment", "Miss", "SWdens")
hr.dataset <- SWS_data[miss.data]

hr.mph <- fa.dataset[which(hr.dataset$Treatment == c('PLA', 'MPH')), ]
hr.atm <- fa.dataset[which(hr.dataset$Treatment == c('PLA', 'ATM')), ]
hr.cit <-fa.dataset[which(hr.dataset$Treatment == c('PLA', 'CIT')), ]
   
##agregates
fa.aggM <- aggregate(. ~ SubID+Treatment, data = fa.mph, FUN = mean)
fa.aggA <- aggregate(. ~ SubID+Treatment, data = fa.atm, FUN = mean)
fa.aggC <- aggregate(. ~ SubID+Treatment, data = fa.cit, FUN = mean)

miss.aggM <- aggregate(. ~ SubID+Treatment, data = miss.mph, FUN = mean)
miss.aggA <- aggregate(. ~ SubID+Treatment, data = miss.atm, FUN = mean)
miss.aggC <- aggregate(. ~ SubID+Treatment, data = miss.cit, FUN = mean)

hr.aggM <- aggregate(. ~ SubID+Treatment, data = hr.mph, FUN = mean)
hr.aggA <- aggregate(. ~ SubID+Treatment, data = hr.atm, FUN = mean)
hr.aggC <- aggregate(. ~ SubID+Treatment, data = hr.cit, FUN = mean)
```

```{r}
#GRAPH FOR EACH TREATMENT 

##Scatterplot of slow wave density and false alarm per treatment 
ggplot(fa.aggM, aes (x = SWdens, y = FA, colour = Treatment)) + geom_point(alpha = .6, size = 2.7)+ geom_smooth(method=lm, se = FALSE)+ scale_colour_manual(values = c("#666666", "#d95f02"))

ggplot(fa.aggA, aes (x = SWdens, y = FA, colour = Treatment)) + geom_point(alpha = .65, size = 2.7)+ geom_smooth(method=lm, se = FALSE)+ scale_colour_manual(values = c("#666666", "#7570b3"))

ggplot(fa.aggC, aes (x = SWdens, y = FA, colour = Treatment)) + geom_point(alpha = .65, size = 2.7)+ geom_smooth(method=lm, se = FALSE)+ scale_colour_manual(values = c("#666666", "#1b9e77"))

##Scatterplot of slow wave density and misses per treatmenr 
ggplot(miss.aggM, aes (x = SWdens, y = FA, colour = Treatment)) + geom_point(alpha = .6, size = 2.7)+ geom_smooth(method=lm, se = FALSE)+ scale_colour_manual(values = c("#666666", "#d95f02"))

ggplot(miss.aggA, aes (x = SWdens, y = FA, colour = Treatment)) + geom_point(alpha = .65, size = 2.7)+ geom_smooth(method=lm, se = FALSE)+ scale_colour_manual(values = c("#666666", "#7570b3"))

ggplot(miss.aggC, aes (x = SWdens, y = FA, colour = Treatment)) + geom_point(alpha = .65, size = 2.7)+ geom_smooth(method=lm, se = FALSE)+ scale_colour_manual(values = c("#666666", "#1b9e77"))

##Scatterplot of slow wave density and reaction time per treatment 
ggplot(hr.aggM, aes (x = SWdens, y = FA, colour = Treatment)) + geom_point(alpha = .6, size = 2.7)+ geom_smooth(method=lm, se = FALSE)+ scale_colour_manual(values = c("#666666", "#d95f02"))

ggplot(hr.aggA, aes (x = SWdens, y = FA, colour = Treatment)) + geom_point(alpha = .65, size = 2.7)+ geom_smooth(method=lm, se = FALSE)+ scale_colour_manual(values = c("#666666", "#7570b3"))

ggplot(hr.aggC, aes (x = SWdens, y = FA, colour = Treatment)) + geom_point(alpha = .65, size = 2.7)+ geom_smooth(method=lm, se = FALSE)+ scale_colour_manual(values = c("#666666", "#1b9e77"))
```