---
title: "mediation_analysis"
author: "Elaine P."
date: "28/04/2021"
output: html_document
---

```{r}
library(ggplot2)
library(ggpubr)
library(car)
library(haven)
library(data.table)
library(visreg)
library(dplyr)
library(tidyr)
library(reshape2)
library(rstatix)
library(JWileymisc)
library(lme4)
library(lmerTest)
#library(multilevelTools)
library(tidyverse)
library(mediation)

        
SWS_data <- read.table("../Tables/CTET_SWdetection_thr90_byE_P2P_avDens_behav_vec_v6_CLUSTERS.txt", header = TRUE, sep = ",", stringsAsFactors = FALSE)

names(SWS_data)[names(SWS_data) == "Drug"] <- "Treatment"

SWS_data$Treatment<-as.factor(SWS_data$Treatment)

SWS_data$Treatment<-relevel(SWS_data$Treatment,"PLA")

nsims<-10000

```

```{r}

SWS_data3<-SWS_data[SWS_data$Treatment=="PLA" | SWS_data$Treatment=="MPH",] #|: . $: and
SWS_data3<-SWS_data3[is.na(SWS_data3$Hit_RT)==FALSE,]
SWS_data3$Treatment<-droplevels(SWS_data3$Treatment)

### Neg MPH on RT
summary(lmer(C_Neg_MPH  ~ 1 + Treatment + (1|SubID), data = SWS_data3))
summary(lmer(Hit_RT  ~ 1 + C_Neg_MPH + (1|SubID), data = SWS_data3))

### Neg MPH on SD RT
summary(lmer(C_Neg_MPH  ~ 1 + Treatment + (1|SubID), data = SWS_data3))
summary(lmer(STD_RT  ~ 1 + C_Neg_MPH + (1|SubID), data = SWS_data3))


## Neg MPH on misses 
summary(lmer(C_Neg_MPH  ~ 1 + Treatment + (1|SubID), data = SWS_data3))
summary(lmer(Miss  ~ 1 + C_Neg_MPH + (1|SubID), data = SWS_data3))


## Neg MPH on FA
summary(lmer(C_Neg_MPH  ~ 1 + Treatment + (1|SubID), data = SWS_data3))
summary(lmer(FA  ~ 1 + C_Neg_MPH + (1|SubID), data = SWS_data3))


```

```{r}
SWS_data4<-SWS_data[SWS_data$Treatment=="PLA" | SWS_data$Treatment=="ATM",] 
SWS_data4<-SWS_data4[is.na(SWS_data4$Hit_RT)==FALSE,]
SWS_data4<-SWS_data4[is.na(SWS_data4$STD_RT)==FALSE,]
SWS_data4$Treatment<-droplevels(SWS_data4$Treatment)

### Neg ATM on RT
summary(lmer(C_Neg_ATM  ~ 1 + Treatment + (1|SubID), data = SWS_data4))
summary(lmer(Hit_RT  ~ 1 + C_Neg_ATM + (1|SubID), data = SWS_data4))


### Neg ATM on SD RT
summary(lmer(C_Neg_ATM  ~ 1 + Treatment + (1|SubID), data = SWS_data4))
summary(lmer(STD_RT  ~ 1 + C_Neg_ATM  + (1|SubID), data = SWS_data4))


## Neg ATM on misses 
summary(lmer(C_Neg_ATM  ~ 1 + Treatment + (1|SubID), data = SWS_data4))
summary(lmer(Miss  ~ 1 + C_Neg_ATM + (1|SubID), data = SWS_data4))

## Neg ATM on FA
summary(lmer(C_Neg_ATM  ~ 1 + Treatment + (1|SubID), data = SWS_data4))
summary(lmer(FA  ~ 1 + C_Neg_ATM  + (1|SubID), data = SWS_data4))


```

```{r}
### Pos ATM on RT
summary(lmer(C_Pos_ATM  ~ 1 + Treatment + (1|SubID), data = SWS_data4))
summary(lmer(Hit_RT  ~ 1 + C_Pos_ATM  + (1|SubID), data = SWS_data4))

### Pos ATM on SD RT
summary(lmer(C_Pos_ATM  ~ 1 + Treatment + (1|SubID), data = SWS_data4))
summary(lmer(STD_RT  ~ 1 + C_Pos_ATM  + (1|SubID), data = SWS_data4))

## Pos ATM on misses 
summary(lmer(C_Pos_ATM  ~ 1 + Treatment + (1|SubID), data = SWS_data4))
summary(lmer(Miss  ~ 1 + C_Pos_ATM  + (1|SubID), data = SWS_data4))


## Pos ATM on FA
summary(lmer(C_Pos_ATM  ~ 1 + Treatment + (1|SubID), data = SWS_data4))
summary(lmer(FA  ~ 1 + C_Pos_ATM  + (1|SubID), data = SWS_data4))


```

```{r}
SWS_data5<-SWS_data[SWS_data$Treatment=="PLA" | SWS_data$Treatment=="CIT",] 
#SWS_data5<-SWS_data5[is.na(SWS_data5$Hit_RT)==FALSE,]
SWS_data5$Treatment<-droplevels(SWS_data5$Treatment)


### Pos CIT on RT
summary(lmer(C_Pos_CIT  ~ 1 + Treatment + (1|SubID), data = SWS_data5))
summary(lmer(RT  ~ 1 + C_Pos_CIT  + (1|SubID), data = SWS_data5))


### Pos CIT on SD RT
#summary(lmer(C_Pos_CIT  ~ 1 + Treatment + (1|SubID), data = SWS_data5))
#summary(lmer(STD_RT  ~ 1 + C_Pos_CIT + (1|SubID), data = SWS_data5))

SWS_data5$Miss <- 1 - SWS_data5$RT
## Pos CIT on misses 
summary(lmer(C_Pos_CIT  ~ 1 + Treatment + (1|SubID), data = SWS_data5))
summary(lmer(Miss  ~ 1 + C_Pos_CIT + (1|SubID), data = SWS_data5))



## Pos CIT on FA
summary(lmer(C_Pos_CIT  ~ 1 + Treatment + (1|SubID), data = SWS_data5))
summary(lmer(FA  ~ 1 + C_Pos_CIT + (1|SubID), data = SWS_data5))



```