---
title: "mediation_analysis"
author: "Elaine P."
date: "28/04/2021"
output: html_document
---

```{r}
library(ggplot2)
library(ggpubr)
library(car)
library(haven)
library(data.table)
library(visreg)
library(dplyr)
library(tidyr)
library(reshape2)
library(rstatix)
library(JWileymisc)
library(lme4)
#library(lmerTest)
#library(multilevelTools)
library(tidyverse)
library(mediation)

        
SWS_data <- read.table("../Tables/CTET_SWdetection_thr90_byE_P2P_avDens_behav_vec_v6_CLUSTERS.txt", header = TRUE, sep = ",", stringsAsFactors = FALSE)

names(SWS_data)[names(SWS_data) == "Drug"] <- "Treatment"

SWS_data$Treatment<-as.factor(SWS_data$Treatment)

SWS_data$Treatment<-relevel(SWS_data$Treatment,"PLA")

nsims<-10000

```



```{r}
SWS_data5<-SWS_data[SWS_data$Treatment=="PLA" | SWS_data$Treatment=="CIT",] 
#SWS_data5<-SWS_data5[is.na(SWS_data5$Hit_RT)==FALSE,]
SWS_data5$Treatment<-droplevels(SWS_data5$Treatment)

### Pos CIT

### RT
med.fit0 <- lmer(C_Pos_CIT  ~ 1 + Treatment + (1|SubID), data = SWS_data5[!is.na(SWS_data5$Hit_RT),])
out.fit1 <- lmer(Hit_RT  ~ 1 + C_Pos_CIT * Treatment + (1|SubID), data = SWS_data5[!is.na(SWS_data5$Hit_RT),])
med.out1 <- mediate(med.fit0, out.fit1, treat = "Treatment", mediator = "C_Pos_CIT",boot = FALSE, sims = nsims)
print(' CIT - Hit RT (Positive CIT cluster)')
summary(med.out1)

### SD RT
med.fit0 <- lmer(C_Pos_CIT  ~ 1 + Treatment + (1|SubID), data = SWS_data5[!is.na(SWS_data5$STD_RT),])
out.fit2 <- lmer(STD_RT  ~ 1 + C_Pos_CIT * Treatment + (1|SubID), data = SWS_data5[!is.na(SWS_data5$STD_RT),])
med.out2 <- mediate(med.fit0, out.fit2, treat = "Treatment", mediator = "C_Pos_CIT",boot = FALSE, sims = nsims)
print(' CIT - STD RT (Positive CIT cluster)')
summary(med.out2)

## Misses 
med.fit0 <- lmer(C_Pos_CIT  ~ 1 + Treatment + (1|SubID), data = SWS_data5[!is.na(SWS_data5$Miss),])
out.fit3 <- lmer(Miss  ~ 1 + C_Pos_CIT * Treatment + (1|SubID), data = SWS_data5[!is.na(SWS_data5$Miss),])
med.out3 <- mediate(med.fit0, out.fit3, treat = "Treatment", mediator = "C_Pos_CIT",boot = FALSE, sims = nsims)
print(' CIT - Misses (Positive CIT cluster)')
summary(med.out3)

## FA
med.fit0 <- lmer(C_Pos_CIT  ~ 1 + Treatment + (1|SubID), data = SWS_data5[!is.na(SWS_data5$FA),])
out.fit4 <- lmer(FA  ~ 1 + C_Pos_CIT * Treatment + (1|SubID), data = SWS_data5[!is.na(SWS_data5$FA),])
med.out4 <- mediate(med.fit0, out.fit4, treat = "Treatment", mediator = "C_Pos_CIT",boot = FALSE, sims = nsims)
print(' CIT - FA (Positive CIT cluster)')
summary(med.out4)

## d=prime
med.fit0 <- lmer(C_Pos_CIT  ~ 1 + Treatment + (1|SubID), data = SWS_data5[!is.na(SWS_data5$dprime),])
out.fit5 <- lmer(dprime  ~ 1 + C_Pos_CIT * Treatment + (1|SubID), data = SWS_data5[!is.na(SWS_data5$dprime),])
med.out5 <- mediate(med.fit0, out.fit5, treat = "Treatment", mediator = "C_Pos_CIT",boot = FALSE, sims = nsims)
print(' CIT - dprime (Positive CIT cluster)')
summary(med.out5)

## crit
med.fit0 <- lmer(C_Pos_CIT  ~ 1 + Treatment + (1|SubID), data = SWS_data5[!is.na(SWS_data5$crit),])
out.fit6 <- lmer(crit  ~ 1 + C_Pos_CIT * Treatment + (1|SubID), data = SWS_data5[!is.na(SWS_data5$crit),])
med.out6 <- mediate(med.fit0, out.fit6, treat = "Treatment", mediator = "C_Pos_CIT",boot = FALSE, sims = nsims)
print(' CIT - crit (Positive CIT cluster)')
summary(med.out6)


```